### ISSUE TITLE
[Suggestion] Add a config for refresh rate or explain how change it on the wiki O.O

### ISSUE THREAD

**Issue by teidova21** [overextended/ox_target#10]
The current refresh rate of raycasted entity is pretty so a config to allow server owners or players to set the refresh rate themself would be nice. OxO

**Comment by thelindat** [comment]
What's the issue?

**Comment by teidova21** [comment]
is it possible to allow for faster refresh of target ?
Cause when you're looking around it feels strange having the menu pop only after half a sec when you look at something.
Not really an issue but more like an improvement, idk if it's possible.
