### ISSUE TITLE
up from 0.20 to 0.90ms

### ISSUE THREAD

**Issue by killy60** [overextended/ox_target#100]
can you help me since i redid my base in esx 1.9.4 i have ox_target which goes up from 0.20 to 0.90ms and i have my menus which multiply .   I'm on the latest version of ox_target

https://i.imgur.com/GkkxSuD.png

https://i.imgur.com/tkb26Fs.png

here is the export for ox_target

CreateThread(function()
			while true do
				Wait(0)
				local interval = true
				local playerCoords = GetEntityCoords(PlayerPedId())
				for k,v in pairs (Config.Bosscybert) do
					local distance = #(playerCoords - v.Pos1)
					if distance < Config.DrawDistance then interval = false
						if distance < Config.Distance then
							exports.ox_target:addSphereZone({
								coords = v.Pos1,
								radius = 1,
								options = {
									{
										name = 'sphere',
										label = "Accéder au menu boss",
										icon = "fa-sharp fa-solid fa-car",
										event = "esx_cybert:OpenBossMenucybert",
										groups = {cyber=4}
									}
								}
							})
						end
					end
				end
				if interval then
					Wait(500)
				end
			end
		end)

**Comment by killy60** [comment]
I forgot to say that once ox_target is active it remains at a minimum of 0.10ms permanently without another point being activated

**Comment by thelindat** [comment]
> goes up from 0.20 to 0.90ms and i have my menus which multiply

```lua
CreateThread(function()
while true do
Wait(0)
```

_Golly gosh I wonder why??????_

**Comment by killy60** [comment]
> > passe de 0.20 à 0.90ms et j'ai mes menus qui se multiplient
> 
> ```lua
> CreateThread(function()
> while true do
> Wait(0)
> ```
> 
> _Mon Dieu je me demande pourquoi ??????_

could my problem come from this?
