### ISSUE TITLE
maxZ is nil on qb-target.lua

### ISSUE THREAD

**Issue by yankikucuk** [overextended/ox_target#106]
in line 139 value returned nil with console error.

```lua
exportHandler('AddBoxZone', function(name, center, length, width, options, targetoptions)
    local z = center.z

    if not options.useZ then
        z = z + math.abs(options.maxZ - options.minZ) / 2 -- < options.maxZ is nil (tested in qb-core framework after delete qb-target)
        center = vec3(center.x, center.y, z)
    end

    return api.addBoxZone({
        name = name,
        coords = center,
        size = vec3(width, length,
            (options.useZ or not options.maxZ) and center.z or math.abs(options.maxZ - options.minZ)),
        debug = options.debugPoly,
        rotation = options.heading,
        options = convert(targetoptions),
    })
end)
```

was fixed in #33  

any solution for this?

**Comment by thelindat** [comment]
> any solution for this?

Make it NOT NIL?

**Comment by yankikucuk** [comment]
> Make it NOT NIL?

The scripts I use are codes developed by other people, such as ox_target. and a few lines of code were written in the package (as the folder name suggests) to make it compatible. The fact that there are some problems with the default packages that come with `qb-taxijob` and similar frameworks must be the duty of the code developed under the name of compatibility here.

If you are considering making the handling situations in each package the responsibility of the user, there should not be a compatibility package here.

Instead of telling me this, what if you wrote a few more lines of code? Because otherwise there is no point in choosing your package. It makes more sense to spend the time writing my own target than I would spend on handling.

The code written does not fully fulfill its purpose. I wrote it for your information. Clean code isn't just about making code that works.

good luck.

**Comment by thelindat** [comment]
Not my fault that QB can't even manage to use "their" resource correctly. It also _isn't my responsibility_ to provide 100% compatibility for anything, let alone for a framework that steals code and removes copyright notices.

qb-target compatibility is only there _because somebody PR'd it_. If something doesn't work, then _PR a fix_, because I frankly could not give any less shits about it.

**Comment by Griefa** [comment]
> > Make it NOT NIL?
> 
> The scripts I use are codes developed by other people, such as ox_target. and a few lines of code were written in the package (as the folder name suggests) to make it compatible. The fact that there are some problems with the default packages that come with `qb-taxijob` and similar frameworks must be the duty of the code developed under the name of compatibility here.
> 
> If you are considering making the handling situations in each package the responsibility of the user, there should not be a compatibility package here.
> 
> Instead of telling me this, what if you wrote a few more lines of code? Because otherwise there is no point in choosing your package. It makes more sense to spend the time writing my own target than I would spend on handling.
> 
> The code written does not fully fulfill its purpose. I wrote it for your information. Clean code isn't just about making code that works.
> 
> good luck.

Tell me you're brain dead without telling me you're brain dead

**Comment by maalouane** [comment]
> > Make it NOT NIL?
> 
> The scripts I use are codes developed by other people, such as ox_target. and a few lines of code were written in the package (as the folder name suggests) to make it compatible. The fact that there are some problems with the default packages that come with `qb-taxijob` and similar frameworks must be the duty of the code developed under the name of compatibility here.
> 
> If you are considering making the handling situations in each package the responsibility of the user, there should not be a compatibility package here.
> 
> Instead of telling me this, what if you wrote a few more lines of code? Because otherwise there is no point in choosing your package. It makes more sense to spend the time writing my own target than I would spend on handling.
> 
> The code written does not fully fulfill its purpose. I wrote it for your information. Clean code isn't just about making code that works.
> 
> good luck.

Bruh, you are a drama turkish queen!

**Comment by BerkieBb** [comment]
> > > Make it NOT NIL?
> > 
> > 
> > The scripts I use are codes developed by other people, such as ox_target. and a few lines of code were written in the package (as the folder name suggests) to make it compatible. The fact that there are some problems with the default packages that come with `qb-taxijob` and similar frameworks must be the duty of the code developed under the name of compatibility here.
> > If you are considering making the handling situations in each package the responsibility of the user, there should not be a compatibility package here.
> > Instead of telling me this, what if you wrote a few more lines of code? Because otherwise there is no point in choosing your package. It makes more sense to spend the time writing my own target than I would spend on handling.
> > The code written does not fully fulfill its purpose. I wrote it for your information. Clean code isn't just about making code that works.
> > good luck.
> 
> Tell me you're brain dead without telling me you're brain dead

Tell me you crave attention without telling me

**Comment by SKITTLE6969** [comment]
> > Make it NOT NIL?
> 
> The scripts I use are codes developed by other people, such as ox_target. and a few lines of code were written in the package (as the folder name suggests) to make it compatible. The fact that there are some problems with the default packages that come with `qb-taxijob` and similar frameworks must be the duty of the code developed under the name of compatibility here.
> 
> If you are considering making the handling situations in each package the responsibility of the user, there should not be a compatibility package here.
> 
> Instead of telling me this, what if you wrote a few more lines of code? Because otherwise there is no point in choosing your package. It makes more sense to spend the time writing my own target than I would spend on handling.
> 
> The code written does not fully fulfill its purpose. I wrote it for your information. Clean code isn't just about making code that works.
> 
> good luck.

are you like brain dead or something bruhhhhhhh? wew there goes the qb-target support CONGRATS buddy
