### ISSUE TITLE
[Suggestion] Adding the DrawSprite to addModel, addEntity, and addLocalEntity.

### ISSUE THREAD

**Issue by rayzenoam** [overextended/ox_target#107]
Hello there, Overextended,
I believe it would be helpful and necessary to add DrawSprite to the addModel, addEntity, and addLocalEntity functions.

Thank you in advance!

**Comment by thelindat** [comment]
https://github.com/overextended/ox_target/issues/15
https://github.com/overextended/ox_target/pull/82
