### ISSUE TITLE
Not getting the netID correctly when being passed into canInteract

### ISSUE THREAD

**Issue by Envi-Scripts** [overextended/ox_target#108]
Hey there, noticed an issue in the latest version that is causing one of my resources to have issues, here is the use case. Have been recommending v1.11.1 as the issue is not present there

canInteract = function(entity)
 local netId = NetworkGetNetworkIdFromEntity(entity) 
   return spawnedMethlab[netId] and not busy 
 end

**Comment by thelindat** [comment]
Huge info dump right there so I know exactly what problem you're experiencing and what you expect to actually happen - you have my deepest thanks.

**Comment by Envi-Scripts** [comment]
Thought it was pretty self-explanatory in the title.

I cannot get the netID from the entity passed through the canInteract function...

**Comment by Envi-Scripts** [comment]
canInteract = function(entity)
local netId = NetworkGetNetworkIdFromEntity(entity)                  -- this netID is always 0
return spawnedMethlab[netId] and not busy
end

**Comment by thelindat** [comment]
I don't know what you expect me to do? I don't even know what code you're running, what the entity is, if there's even an entity, if the entity is networked. I also didn't create the native function which gets a netid from an entity, nor did I write the native that gets the entity id in the first place.

**Comment by Envi-Scripts** [comment]
Idk man, only tryna help..

**Comment by thelindat** [comment]
You're the one experiencing and reporting an issue; such things require information.

**Comment by Envi-Scripts** [comment]
I guess this is as much info as I can get on the limited time that I have

Test code: 


```
local testZone = exports.ox_target:addSphereZone({
    coords = vector3(-1361.0247, -579.1785, 29.79), --z = 3.0
    size = vector3(5,5,5),
    rotation = 300,
    debug = true,
    options = {
        {
            name = "doorbell",
            label = "Test",
            onSelect = function()
                print('test')
            end,
            canInteract = function(entity)
                print('entity', entity)
                local netId = NetworkGetNetworkIdFromEntity(entity)
                print('netID', netId)
            end,
            icon = "fas fa-bell",
        },
    },
})
```

Result on v1.11.1: 
![image](https://github.com/overextended/ox_target/assets/126303539/3a49145d-f401-4595-8ecd-602260dcef3c)


Result on latest version: 
![image](https://github.com/overextended/ox_target/assets/126303539/4d8b2b04-827a-4926-93c4-c210b849f8d7)

**Comment by benzon** [comment]
https://github.com/overextended/ox_target/blob/4c2c924f0b0d20838acf8475d34aac19f3d86538/client/main.lua#L240

Looked into this reported issue, and it looks like a minor oversight, after the rework on zone handling.

Entity is never sent over, and it should be a pretty easy fix.

local hide = shouldHide(option, distance, endCoords, entityHit)

@thelindat
