### ISSUE TITLE
[Suggestion] Automatic release workflow

### ISSUE THREAD

**Issue by ChatDisabled** [overextended/ox_target#11]
Always pulling the latest release like [so](https://github.com/overextended/ox_target/releases/latest/download/ox_target.zip) doesn't work unlike [ox_lib](https://github.com/overextended/ox_lib/releases/latest/download/ox_lib.zip). Also if downloaded through `https://github.com/overextended/ox_target/archive/refs/tags/v1.1.3.zip` the resulting folder will always be `ox_target-release_tag` (As expected). Which will require people to manually rename it back to `ox_target` to make the exports work.

So can we also get automatic release [workflow](https://github.com/overextended/ox_lib/blob/master/.github/workflows/release.yml) in here please :D. I know that it's more so of a personal request but would help with the recipe deployer. My knowledge on GitHub CI is near nothing otherwise I would've PR'd it.

**Comment by LukeWasTakenn** [comment]
👍

**Comment by LukeWasTakenn** [comment]
Implemented in commit b2f37e27b8e26b4a2c0e32cd5676507ca1152cd4
