### ISSUE TITLE
Optimization BUG

### ISSUE THREAD

**Issue by zeppyscripts** [overextended/ox_target#115]
so, i like watch the framerates all the time,
tested hundreds of times
i know u said this 4x more optimized than qb-target
but oh boy. 
i guess theres a line somewhere that causes the occasional quick frame rate drop. every 15 secs or so.

i will update if i find it
for now im switching back to qb-target.

**Comment by jag3dagster** [comment]
You're going to have to be a bit more specific here. If you want anything to come of this ticket.

- Define: "quick frame rate drop"
- Explain how many targets you have set up on your server.
- Does this happen at any given time or only when you have the target active?
- Try capturing this performance dip in the Perf Profiler to see if you can't narrow down what is occurring

**Comment by thelindat** [comment]
> * narrow down what is occurring

see: endlessly re-registering targets in loops/events
