### ISSUE TITLE
Overall distance never higher than 7

### ISSUE THREAD

**Issue by JustMordeckai** [overextended/ox_target#116]
I actually noticed on line 167 of the client-side main.lua that the distance was forced to 7, so when we set a distance on our target options greater than 7, it's never taken into account. For props this might be understandable, but for large polyZones it forces you to look at the floor, ceiling, wall or props less than 7 away. Logically, if I'm in a fairly large zone, and the target is pointing at the floor of the same zone that's more than 7 away from me, I should be able to access it.

**Comment by thelindat** [comment]
> fairly large zone

I'd personally never use _large zones_ as targets, and I don't want to remove a _rather reasonable_ restriction on target distance.
