### ISSUE TITLE
Bone targeting does not work as expected

### ISSUE THREAD

**Issue by SneakyAF** [overextended/ox_target#12]
For some reason, all of the options merge and are visible on bones that shouldn't even have an option. Not sure if I'm using the export wrong or what is going on.

This my sample code for targeting **engine** and a **rear right wheel**

<img width="322" alt="mstsc_mM3y2JebVJ" src="https://user-images.githubusercontent.com/45791897/193426917-b355cee0-b485-4f5f-891e-f301d632db11.png">

Next, when in-game I see this:

**Targeting engine**
![image](https://user-images.githubusercontent.com/45791897/193426942-be9768d9-ed3c-43b2-92aa-33a84d96f465.png)

**Targeting rear right wheel**
![image](https://user-images.githubusercontent.com/45791897/193426963-2f43bbe4-08fb-4513-a937-34a78db80edd.png)

**Targeting front right wheel (this shouldn't even have options)**
![image](https://user-images.githubusercontent.com/45791897/193426987-e6226be7-ed66-45af-b271-563e8bcee9db.png)

Am I doing something wrong or is this a bug?

**Comment by thelindat** [comment]
https://github.com/overextended/ox_target/commit/91ef33b3d6b2973015f4edccb2aad9a62feff231
https://github.com/overextended/ox_target/commit/18bfa9e6e24c701950750f6ee6f9e39068fa4509
