### ISSUE TITLE
Nil value

### ISSUE THREAD

**Issue by BeardedSavage** [overextended/ox_target#131]
When installed and all inventory, none of my mechanic jobs, or ems jobs have items in there shop or armory. Upon further evaluation with F8, it tells me "attemt to perform arithmatic on nil value (field 'ammount'). I looked in the file system it directed me to and found no errors. The file process says @qb-target/client/framework/qb.lua:17. Any ideas?

**Comment by tomigatica15** [comment]
fix
https://github.com/overextended/ox_target/pull/130
