### ISSUE TITLE
Notify ox system in qbcore 

### ISSUE THREAD

**Issue by Rolyt1212** [overextended/ox_target#140]
how can i make to have ox notify in qbcore

**Comment by tom-osborne** [comment]
https://overextended.dev/ox_lib/Modules/Interface/Client/notify

**Comment by Rolyt1212** [comment]
i dont understend what and where i have to put

**Comment by WooAf** [comment]
> i dont understend what and where i have to put

qb-core -> client -> functions.lua -> QBCore.Functions.Notify
