### ISSUE TITLE
Expected options to have type 'array' (received hash table)

### ISSUE THREAD

**Issue by TuneScotty** [overextended/ox_target#148]
I thought the convert function solves it, what else can I do to fix it?
![image](https://github.com/overextended/ox_target/assets/87590971/5bed5618-a677-40bf-9166-7e277fe8ad46)
Here's how the table looks like:
![image](https://github.com/overextended/ox_target/assets/87590971/9cf85849-74d0-4a8b-a7d8-9a6226adef66)
And here's the ox_target event handler:
![image](https://github.com/overextended/ox_target/assets/87590971/53942405-3983-4022-9a3f-00db4d5dd244)

**Comment by thelindat** [comment]
`addLocalEntity` and `AddTargetEntity` are notably different things and call different functions.

**Comment by TuneScotty** [comment]
> `addLocalEntity` and `AddTargetEntity` are notably different things and call different functions.

How calm I missed that.. that's embarrassing, anyway what did fix it is referring to qb-target, not the ox_target..
