### ISSUE TITLE
[Suggestion] Draw sprites for all interactables

### ISSUE THREAD

**Issue by SneakyAF** [overextended/ox_target#15]
Thus far the circle sprites are drawn only for zones. This is such a great feature and would love to see it on other interactables such as entities, bones etc. 

Would this be possible ?

**Comment by thelindat** [comment]
This would be rather taxing, as we'd roughly need to
- GetGamePool 3x for ped, object, and vehicles
- Get the model for each entity in the three game pools
- Get the coords and distance for each entity
- Check if the model can be interacted with (basically always if using global options)
- Draw sprites for potentially hundreds of entities every frame

**Comment by SneakyAF** [comment]
`Draw sprites for potentially hundreds of entities`

This is the only one I slightly disagree - distance check should save us from drawing hundreds of them at the same time. 

Unless of course we are standing next to hundreds of interactables.


All of the other points do make sense and I can see how quickly it could become expensive.

Maybe a way to configure them separately? Sperate cvar for peds,vehicles, models. So that only certain types could be set to have a sprite (props are usually stationary for example).

This is just an idea and nothing game breaking if not implemented. It's just that having this for zones "spoiled" me and I now use the target to sort of check if anything around me is interactable or not 😊

**Comment by thelindat** [comment]
Even if it's something configurable I don't see it as something overly beneficial. Basically every entity is "interactable", at the very least every vehicle would always have a sprite being drawn when in range; once you add a global option to ped then they all get a sprite as well.

Sure it can be optional and disabled by default, but it loses any value once every entity is interactable.

**Comment by SneakyAF** [comment]
Understood, thank you for the discussion and precise explanation 👌
