### ISSUE TITLE
Search through the eye, with the ox_inventory inventory

### ISSUE THREAD

**Issue by MrGongal** [overextended/ox_target#151]
![image](https://github.com/overextended/ox_target/assets/140329673/bbb219a4-0885-430c-9081-79ee9170c5a3)
![image](https://github.com/overextended/ox_target/assets/140329673/5551c1ad-50f0-49e1-ae5f-6c2a7d6beb20)

**Comment by MrGongal** [comment]
Help?

**Comment by CeebDev** [comment]
GH issues are not for support, go discord

**Comment by thelindat** [comment]
> Help?

No?
