### ISSUE TITLE
Getting texture error after updating ox lib, ox target

### ISSUE THREAD

**Issue by Shafat21** [overextended/ox_target#157]
I can't select from menu, Also tried to refresh file. Cleared cache still facing same issue
Check this [Image](https://cdn.discordapp.com/attachments/1258858132520702115/1258858132827013321/image.png?ex=668ae3ff&is=6689927f&hm=6ceaeb747738c91138b69d0ab254c2172dad587ca1419d6e09762588dc9c3615&)

**Comment by Shafat21** [comment]
![image2](https://github.com/overextended/ox_target/assets/61838416/b892845f-8b24-4e05-b90c-34990a8a2953)
![image](https://github.com/overextended/ox_target/assets/61838416/21ca3f81-9aee-4f6a-bdd9-6b1a22a7dd34)

**Comment by thelindat** [comment]
![image](https://github.com/overextended/ox_target/assets/65407488/24836307-c071-4a23-99c0-690b1c26d041)
