### ISSUE TITLE
[Suggestion] AddEntityZone support from qtarget.

### ISSUE THREAD

**Issue by SneakyAF** [overextended/ox_target#16]
Is this something doable? Or was it dropped because of being expensive?

Few of the resources I use are based on this function so it would be great if I could use them with ox_taget without messing around trying to replace them with some sort of different type of zone

**Comment by thelindat** [comment]
Entity zones would need to be implemented in ox_lib to support them here.
Most people use entity zone where you can just use addEntity or addLocalEntity, so you should consider if you can swap there.

**Comment by SneakyAF** [comment]
Got it, going to try replacing it with something already implemented, thank you

**Comment by SneakyAF** [comment]
Found a solution that works, thank you

**Comment by bl0ody41** [comment]
how you do that bro
