### ISSUE TITLE
Bug or Adjustments or Question? 

### ISSUE THREAD

**Issue by kikyre** [overextended/ox_target#17]
My last issue created it is not very clear but right now i found it

when i was using a qtarget i dont have a minZ and maxZ Set in my exports so when i put ox_target some of my scripts that does not have a minZ and maxZ set does not work, but when i put minZ and maxZ in the scripts that are not showing using ox target it now finally works, so do i need to put each of my scripts a minZ and maxZ?

--------
1st Image 
This is a Code of qtarget that does not work when using ox_target this is without minZ and maxZ
![image](https://user-images.githubusercontent.com/92689671/194125033-c1f02da6-7067-42e7-a53d-9c8d2e29062d.png)
--------
2nd Image
This is a Code of qtarget that works using ox_target with minZ and maxZ
![image](https://user-images.githubusercontent.com/92689671/194125217-c6172fe1-c0ac-4d76-9a98-47344b24c479.png)

Sorry i just randomize the minZ and maxZ just to check if it requires a minZ or maxZ to work each script for test only

**Comment by thelindat** [comment]
qtarget used maxZ/minZ for boxzones, so I don't know what you're complaining about.
It's also not an ox_target issue.
