### ISSUE TITLE
Scrollbar appears when the list options is very long

### ISSUE THREAD

**Issue by SneakyAF** [overextended/ox_target#19]
The issue I constantly run into is that at certain times more than one bone is being targeted causing the options from all of them to appear.

For example, in this image, a total of 3 bones are targeted - **engine, left front wheel, right front wheel**

![ShareX_FV9GN4AeHm](https://user-images.githubusercontent.com/45791897/194545858-6e0c7441-c509-4eaa-9962-6deadb71860d.jpg)

This causes an extensive list of options to appear. Is it possible that in such cases only a single bone would be targeted and only its options displayed? Also noticed that a scrollbar appears when the list options is very long.

Preferably only the table marked red would be visible in this example

**Comment by thelindat** [comment]
Reduce the distance for your options.

**Comment by SneakyAF** [comment]
> Reduce the distance for your options.

Yeah that worked, sorry for not figuring this out myself. 

What about the scroll bar? Is this something that could be disabled when the list is long?
