### ISSUE TITLE
ox_target performance problems up to 0.50ms

### ISSUE THREAD

**Issue by soniXx123** [overextended/ox_target#20]
Hello, 

we moved from qtarget (0.01/0.03ms) to your new ox_target (0.10/0.50ms) and we have now good performance usage from it and this is all the time. Any idea about it? 

![image](https://user-images.githubusercontent.com/35350615/194694314-fc9b3d58-0844-4e40-9e88-3a4681a785cb.png)

**Comment by thelindat** [comment]
By itself it runs at 0.01; but it provides api for you to run your own code. Without knowing what you’re doing I can’t tell you what you’re doing wrong.

Usual recommendation is to ensure no debug zones.

**Comment by thelindat** [comment]
User was registering targets in a loop.
