### ISSUE TITLE
Qtarget to Ox_target

### ISSUE THREAD

**Issue by Knockz1** [overextended/ox_target#22]
I switched from qtarget to ox_target and now my Goodlife script will not work. It says this "No Such Export AddEntityZone in resource qtarget" is there any way i can fix this error?

**Comment by BerkieBb** [comment]
Yes, you can convert it to use ox_target

**Comment by Knockz1** [comment]
> Yes, you can convert it to use ox_target

Ok i will try that

**Comment by Knockz1** [comment]
> Yes, you can convert it to use ox_target

Says the same thing

**Comment by BerkieBb** [comment]
Then you didn't convert it

**Comment by Knockz1** [comment]
> Then you didn't convert it

you think, you will be able to tell me how?

**Comment by BerkieBb** [comment]
I won't, the docs will if you read it correctly
