### ISSUE TITLE
qb-compat for AddTargetEntity not functioning, does not create target

### ISSUE THREAD

**Issue by jellyton69** [overextended/ox_target#27]
Targets that are registered using AddTargetEntity are not working at all. I've tested this with qb-garbage job for the ped, and qb-hotdogjob with the hotdog stand.

**Comment by thelindat** [comment]
@BerkieBb

**Comment by BerkieBb** [comment]
I found why, the compat uses addTargetEntity, but that always requires the entity to be networked whilst the AddTargetEntity export of qb-target accepts unnetworked entities as well
