### ISSUE TITLE
Use OX Target for objects

### ISSUE THREAD

**Issue by akiilles05** [overextended/ox_target#3]
One problem I have is that when I use the ox target on objects, the option gets duplicated a lot.

**Comment by akiilles05** [comment]
I use it like this
![image](https://user-images.githubusercontent.com/112715362/188191892-4ed51daf-9621-4060-8e94-1b02a3c3213f.png)

**Comment by thelindat** [comment]
Yes you’re registering a new option everytime you trigger your function.

**Comment by akiilles05** [comment]
How to fix this problem?

**Comment by akiilles05** [comment]
Okay, can you send me an example of this?

**Comment by akiilles05** [comment]
Okay, can you send me an example of this?

**Comment by thelindat** [comment]
...

Remove
![image](https://user-images.githubusercontent.com/65407488/188224079-d7b03c00-d3e9-493e-8f3b-9b803db4e766.png)

from this
![image](https://user-images.githubusercontent.com/65407488/188224053-3af53eb4-03d2-47b1-ae96-d0a2766f55b3.png)

**Comment by akiilles05** [comment]
Where shoud I type these lines?
