### ISSUE TITLE
Suggestion - Allow passing of variables or variable in event

### ISSUE THREAD

**Issue by DubStepMad** [overextended/ox_target#4]
Implement the ability by default to pass variable values for events.

I have previously implemented this on qtarget before and moving over I would like this to be something that is provied by default.

I personally found it best to pass one variable which then can contain all the data being nested.

**Examples:**

Current:
```
{
    event = "test:Check",
    icon = "fas fa-id-card",
    label = "Test",
    canInteract = function(entity, coords, distance)
        return true
    end
},
```

Implementation:

```
local data =  {
    testingMode = false,
    values = {
        val1 = "test1",
        val2 = "test2"
    }
}
```

...

```
{
    event = "test:Check",
    data = data,
    icon = "fas fa-id-card",
    label = "Test",
    canInteract = function(entity, coords, distance)
        return true
    end
},
```

Can see where I am going with this.

**Comment by thelindat** [comment]
What's the point, you're already defining the data. Assign it to a local or table inside your resource, instead of sending it to ox_target and having it sent back.

**Comment by DubStepMad** [comment]
> What's the point, you're already defining the data. Assign it to a local or table inside your resource, instead of sending it to ox_target and having it sent back. The point of ox_target is to stop horrible design patterns that people constantly implement
> 
> In fact, this should already be possible, despite being pointless in most situations (I believe it's solely there for the sake of backwards-compatibility). ![image](https://user-images.githubusercontent.com/65407488/189556265-64b3712e-0d8c-438e-8958-909adb9fbafd.png) ![image](https://user-images.githubusercontent.com/65407488/189556267-430d7798-a515-47c2-855c-cf609fcab7e0.png)

I think you misunderstood my idea.

This data can be dynamic and change from the resource calling it to the resource aimed to receieve it.

if we go to basics.

**test.lua**
```
function (type)
   if type == "type1" then
       return SOMETHINGHERE
   elseif type == "type2" then
       return SOMETHINGHERE
   elseif type == "type3" then
       return SOMETHINGHERE
   end
end
```

rather than making 3 different events for this function we can make one that passes the `type` value.

In the end it reduces duplicated code with minor tweaks.
