### ISSUE TITLE
[Bug?] Issues with player / ped detection

### ISSUE THREAD

**Issue by benzon** [overextended/ox_target#44]
Hey,

So we use shell (props) for housing, i a person dies with in a shell, we cant target them via ox_target in any way, it's like the shell prop creates some sort of issue picking op the target, qtarget did not have this issue, so not sure if the method used to identify targets, is off in some way.

**Comment by thelindat** [comment]
If you haven’t then update to the latest version

**Comment by benzon** [comment]
Okay found a nother issue with newest version tho

Not sure if this is by design, before the update they picked up fine, now i have to extend the box outside of the desk

https://user-images.githubusercontent.com/3528000/202849803-929ad147-142f-400d-98a6-60a8676cf1f6.mp4

https://user-images.githubusercontent.com/3528000/202849807-7fecbbcb-b37e-40a7-bbdc-303699d2813f.mp4

**Comment by thelindat** [comment]
why is it a box zone

**Comment by benzon** [comment]
Since before it would not pick up the peds either, it refused, so we had to make it in to a box zone.

**Comment by thelindat** [comment]
Seems to me like there's still collision in the gap.
![image](https://user-images.githubusercontent.com/65407488/202935206-6af17314-2ba8-4c60-a793-71199b3b5d1f.png)
