### ISSUE TITLE
Qidentifcation

### ISSUE THREAD

**Issue by xJkaay** [overextended/ox_target#48]
is there a way to get this script to work with ox_target

**Comment by xJkaay** [comment]
exports['qtarget']:AddEntityZone("license", spawnedPed, {
						name="license",
						heading=GetEntityHeading(spawnedPed),
						debugPoly=false,
					},  
this is current

**Comment by N-fire** [comment]
You will find everything you need in the documentation.
https://overextended.github.io/docs/ox_target
