### ISSUE TITLE
"Bubble" missing on the dumpster

### ISSUE THREAD

**Issue by SneakyAF** [overextended/ox_target#5]
When using the system a bunch of points appear on the screen ( I assume those are interaction points for the eye).

However, the dumpster, that is interactable does not have one.
![image](https://user-images.githubusercontent.com/45791897/190873500-a45c5729-88c4-43f0-a139-fc6b6d56c36f.png)
![image](https://user-images.githubusercontent.com/45791897/190873519-fd3311d4-85e8-4b93-90f9-87dd48e4a7dd.png)

In addition, is there a way to control the distance for those bubbles? The amount of them on the screen looks a little bit excessive 

Ox_target + Ox_inventory with targeting system used in the screenshots

**Comment by thelindat** [comment]
The sprites appearing everywhere is actually unintended, and furthermore they only draw for zones.
Dumpsters aren't zones so they don't get the sprite.

**Comment by SneakyAF** [comment]
Understood, so I assume the sprites is considered as bug and will be fixed in the future updates?
