### ISSUE TITLE
target is buggy

### ISSUE THREAD

**Issue by Kevinindy2k** [overextended/ox_target#52]
get a mouse cursor to show up when clicking LMB with the target up regardless of if that target is over something with options

**Comment by thelindat** [comment]
Not a bug; when you click it enables NUI. Don't see how that's an issue either.

**Comment by Kevinindy2k** [comment]
In Ux ,it not good sir can u make it like qtarget?

**Comment by thelindat** [comment]
In _your opinion_ "it not good".
