### ISSUE TITLE
[Bug] Debugs are not removed on Zone Removal

### ISSUE THREAD

**Issue by Mkeefeus** [overextended/ox_target#53]
![image](https://user-images.githubusercontent.com/27903055/209752115-cdc02fb0-ca22-49bc-a370-ffc6a40b2660.png)

When a zone is removed, the debug draws don't seem to be removed as well. In the screen shot the zones themselves are not present as I can't target the stands, but the spheres are still there, and sometimes would double up when the resource is started again (see below)

![image](https://user-images.githubusercontent.com/27903055/209752248-b2f43b45-7b9a-44ad-abc3-835fa0abb275.png)

**Comment by thelindat** [comment]
Was an ox_lib issue and has been resolved.
