### ISSUE TITLE
[bug] item restriction fails after first success

### ISSUE THREAD

**Issue by Manason** [overextended/ox_target#57]
On qb-core and ox_target v.1.6.3, set a target option to require an item. On acquiring the item, the target is visible. Then after dropping the item, the target is still visible. If I restart ox_target without the item in my inventory, the target is hidden. As soon as I have the item in my inventory, even if I just pick it up and drop it, this will make the target visible and it will not become invisible again.

It appears the behavior operates off of a flag that is flipped to allow the target to be visible instead of checking for the existence of the item every time.

**Comment by thelindat** [comment]
You can look at and see what the problem is yourself. I can't even be bothered testing with my regular server setup, so like hell I'm going to fuss around with anything related to qb-core.

> It appears the behavior operates off of a flag that is flipped to allow the target to be visible instead of checking for the existence of the item every time.

No, it checks `PlayerHasItems` each iteration
