### ISSUE TITLE
Seemingly random ox_doorlock error when targeting random objects

### ISSUE THREAD

**Issue by jellyton69** [overextended/ox_target#59]
Not entirely sure if this is an ox_target or ox_doorlock issue, however when targeting objects, there's chance of the script erroring, which results in your cursor being stuck on your screen in rare cases, and your targeting cursor being stuck in common cases.

```
[  14012485] [b2699_GTAProce]             MainThrd/ ^1SCRIPT ERROR: @ox_doorlock/client/utils.lua:5: attempt to index a boolean value (local 'data')^7
[  14012485] [b2699_GTAProce]             MainThrd/ ^3> getDoorFromEntity^7 (^5@ox_doorlock/client/utils.lua^7:5)
[  14012485] [b2699_GTAProce]             MainThrd/ ^3> ref^7 (^5@ox_doorlock/client/utils.lua^7:26)
[  14012485] [b2699_GTAProce]             MainThrd/ ^3> fn^7 (^5@ox_target/client/main.lua^7:195)
[  14012485] [b2699_GTAProce]             MainThrd/ ^1SCRIPT ERROR: error object is not a string^7
```

![image](https://user-images.githubusercontent.com/20498875/214465394-0679de19-d423-4f65-bb15-539076b9d2a9.png)

**Comment by thelindat** [comment]
Not a target issue, and not even something I could reproduce in doorlock (fun); but I made a commit that should prevent it.
