### ISSUE TITLE
groups? [Not working?]

### ISSUE THREAD

**Issue by Fellow25** [overextended/ox_target#6]
Hello, I read the documentation, and I am not able to perform the following function:

groups? = string | string[] | { [string]: number }

There is no example on how to do this in the documentation...

I write this:

groups = { ["police"]: 3 }

My question is simple, is the function really implemented or will it be implemented yet?

Sorry for posting there, but i can't join discord...

Thank's.

**Comment by thelindat** [comment]
> i can't join discord
🙄

It is implemented, it's been tested with ox_core and esx, I couldn't give a rats arse about qbus, nor could I care about support for somebody who is blacklisted by Warden.

**Comment by Fellow25** [comment]
Thanks for reponse...

Warden banned me, because a friend of mine had me founder with him, leak server, but I never leaked any, I just made or edited existing scripts, nothing more...
