### ISSUE TITLE
Getting stuck with an Error

### ISSUE THREAD

**Issue by kikyre** [overextended/ox_target#67]
![Screenshot_395](https://user-images.githubusercontent.com/92689671/222536489-87192a9a-331b-4010-99cb-7e0e5c5fe2cd.png)

Some of my Players are getting Error where the UI is getting Stuck in the middle where it show a Native Error Something Related to GetEntity i was wondering if there is something wrong with the artifacts i just recently updated the artifacts same with the latest version of ox_target but still persist, sorry for this i hope you can help me

**Comment by thelindat** [comment]
Happen to know what you're targeting when this occurs?

**Comment by kikyre** [comment]
> 

no, there is no targeting something when this occurs

**Comment by thelindat** [comment]
Well unless I can repro it, not much to do; I can't even make GetEntityType throw an error even if I send invalid types (i.e. string, nil, boolean, whatever).

**Comment by kikyre** [comment]
> Well unless I can repro it, not much to do; I can't even make GetEntityType throw an error even if I send invalid types (i.e. string, nil, boolean, whatever).

oh, anyway thank you for answering me, i guess i'll go look for a way for a way for the mean time thank you

**Comment by thelindat** [comment]
Somehow selecting an option as it gets removed? Repro always nice but that's a simple enough fix.

**Comment by kikyre** [comment]
Hello, i added this and tested in my test server and it works properly using the qtarget compatibility 
![image](https://user-images.githubusercontent.com/92689671/222550080-a807d7d7-d4d9-4ce4-a3ac-60aab9f65540.png)
also i added this in qtarget.lua 
![image](https://user-images.githubusercontent.com/92689671/222550240-f7f6b173-1fac-4e86-8ab2-a705fe6498e7.png)
And tested in my test server working fine and removed the ( options.useZ ) cause this does not work really well with qtarget exports in my scripts so i am just a waiting an hour for my main server to see if there is a any problem or something i hope this works

**Comment by kikyre** [comment]
Anyway sir i just tested this and it works fine without a problem and my issue is also fix sorry for taking up your time.
