### ISSUE TITLE
Error executing native GetEntityType

### ISSUE THREAD

**Issue by FjamZoo** [overextended/ox_target#76]
Looks like when entity returns 387 we get this error, no idea why the fuck we even get entity 387? But happens randomly when in the server for long periods of time.

Proof of issue
https://streamable.com/k45yhw

In this video I printed the entityHit and I only got the error whenever we hit entity 387.
![Code_VNor4pemxa](https://user-images.githubusercontent.com/34508112/236630828-caff610b-7cfc-42e2-a959-e5995db6491f.png)

Quick fix would be adjust entityType to the following
```lua
entityType = entityHit ~= 0 and entityHit ~= 387 and GetEntityType(entityHit) or 0
```

This just kinda looks a lil more ugly and no idea why entity is 387 and if there's other "entities" where this issue occour?

Here are the server stats, note that it could be a artifact and gamebuild issue but multiple people have reported this in the discord.
Gamebuild 2802
Server artifacts 6379

**Comment by pushkart2** [comment]
![image](https://user-images.githubusercontent.com/10562121/236689699-51e72cef-8c66-4a7e-9683-46c52bc2056a.png)
found a similar issue on entity 130

**Comment by FjamZoo** [comment]
> ![image](https://user-images.githubusercontent.com/10562121/236689699-51e72cef-8c66-4a7e-9683-46c52bc2056a.png) found a similar issue on entity 130
> 
> Server stats - build 2699, artifacts - 6385

Yeah that is odd, i will keep testing to see if I get any other "entities" so far its just been 387

**Comment by thelindat** [comment]
Entities don't have persistent ids.

**Comment by FjamZoo** [comment]
> Entities don't have persistent ids.

Well sometimes I'm retarded, hopefully with the error handling you added this should be fixed
