### ISSUE TITLE
Hello i got this problem and i dont now how to fix it can you help me

### ISSUE THREAD

**Issue by Vianoce** [overextended/ox_target#78]
![20230520124302_1](https://github.com/overextended/ox_target/assets/111280714/3179d23b-f98a-4d3f-94c0-f06309c57b3d)

**Comment by thelindat** [comment]
Nobody can answer the question of how that variable is nil considering _it's always defined_.

https://github.com/overextended/ox_target/blob/2d4692f93355701a67f82d20be186c03a3cd3d88/client/utils.lua#L47
https://github.com/overextended/ox_target/blob/2d4692f93355701a67f82d20be186c03a3cd3d88/client/utils.lua#L92
