### ISSUE TITLE
[Suggestions] Configuring inputs and browsing options

### ISSUE THREAD

**Issue by lexinor** [overextended/ox_target#8]
- I'm not sure how to explain this but something that I found odd is to press right click to display the mouse to be able to select an option. I think that would be a good improvement to change it to left click or maybe to be able to configure it via a config file or convar.

- Also I think that would be great to be able to browse options using the mousewheel, do you think that would be possible ?

Thanks for the reading :)

**Comment by thelindat** [comment]
`setr ox_target:leftClick 1`

**Comment by lexinor** [comment]
> `setr ox_target:leftClick 1`

It's used to not force the left click to set the focus on the menu ?
