### ISSUE TITLE
Ox_Target don’t work after server restart 

### ISSUE THREAD

**Issue by Grosserkill4** [overextended/ox_target#85]
When i restart my Server i have to restart ox_target bevor i can use it i tried to restart the Script at the end of rhe server.cfg but it dont Work can anyone Help me

**Comment by thelindat** [comment]
huge info dump here, i'm sure i'll be able to magically pull a solution out of my arse

**Comment by Grosserkill4** [comment]
What information do you need ?

**Comment by thelindat** [comment]
Framework? Resource load order? Errors? What isn't working? Literally anything?

**Comment by Grosserkill4** [comment]
I use esx 1.9.4 and and get No Errors but when i Press the Button zu aktivste the target nothing Happens but when i restart the Script it worked fine

**Comment by Grosserkill4** [comment]
nerver mind i starded my server and got this error https://gyazo.com/42c19a69decc98349dc118760c503555 but when i restart the script i got no error and i can youse the script

**Comment by thelindat** [comment]
Update the resource.
