### ISSUE TITLE
overlapping targets do not stack

### ISSUE THREAD

**Issue by Senlar** [overextended/ox_target#88]
v1.9.2 ox_target
v3.6.0 ox_libs

![image](https://github.com/overextended/ox_target/assets/1503963/38c5b650-3d4f-4b70-8266-5e84b16929c9)
You can see a PolyZone with a sphere zone inside of it in the above image. The sphere zone is replacing the options instead of adding onto the options along with the ones from the polyz one.

![image](https://github.com/overextended/ox_target/assets/1503963/b66b632a-9f2a-4bdb-9011-05f836910f7b)
Here are the polyzone only options with the target only inside of the polyzone.

![image](https://github.com/overextended/ox_target/assets/1503963/b794864e-977e-4c71-a25e-38c31d172ed7)
Here is what happens when you target inside of the sphere. The polyzone target options go away and are replaced by only the sphere options.

**Comment by thelindat** [comment]
Not supported.

**Comment by haszero** [comment]
I believe fixing this will affect dominance over other replacements that deal with it.

**Comment by thelindat** [comment]
> other replacements that deal with it

I'd love to see this other replacement that handles multiple overlapping zones (considering the poor quality of previous interaction systems).

**Comment by haszero** [comment]
Maybe they don't necessarily have it done, but these projects are not very supported and developed, so I as a user would ask you to introduce this.

**Comment by Senlar** [comment]
Meta Target has it. Missing this feature is the only reason I haven’t moved to ox_target

**Comment by thelindat** [comment]
> Meta Target has it. Missing this feature is the only reason I haven’t moved to ox_target

Personally your screenshots above just seem like an odd usage of the targeting menu (targeting non-specific locations) but as there's some other use-case such as different resources overlapping I've added it.
