### ISSUE TITLE
Not able to target World Props

### ISSUE THREAD

**Issue by vesturo** [overextended/ox_target#9]
Hello,
as described in the Descriptions i struggle to get most world props like "prop_veg_crop_orange" to register via **ox_target:addModel**.
Honestly i don't know if it's a GTA thing or a script thing as i can target others like "prop_truktrailer_01a" just fine.

Would love to know if it's a fixable bug, an error on my end or GTA being GTA, cheers!

example:
`local models = {'ch1_09b_vines_38','ch1_09b_vineslmbs_39'}`
`local options = {}`
`table.insert(options, {
    event = "restart_fruitfarm_oranges:harvest",
    icon = "fas fa-seedling",
    label = "Orangen Pflücken"
  })`
`exports.ox_target:addModel(models, options)`

**Comment by vesturo** [comment]
love the new solution so far tho <3

**Comment by thelindat** [comment]
`ch1_09b_vines_38` doesn't seem to have a hitbox / collision, raycasts go right through it. Nothing I do can change how that works.

**Comment by vesturo** [comment]
> ch1_09b_vines_38 doesn't seem to have a hitbox / collision, raycasts go right through it. Nothing I do can change how that works.

so the best solution probably be a boxZone i guess, thanks for the answer!

**Comment by thelindat** [comment]
Zones still require collision with _something_.
