### ISSUE TITLE
There is no option for an event to pass an args

### ISSUE THREAD

**Issue by guneyct** [overextended/ox_target#93]
We need a option for pass an args to an event

**Comment by jag3dagster** [comment]
No, because that week be a static value in most cases. Use onSelect and trigger the event yourself with whatever args you need to send

**Comment by thelindat** [comment]
Arguments are dynamic, not stupid static values.

```
local mySoCalledArgs = {
    a = 'A',
}

AddEventHandler('myEvent', function(data)
    print(data.entity, mySoCalledArgs.a)
end)
```

Not to mention data contains almost all the data you passed along with your option _anyway_.

**Comment by guneyct** [comment]
It could be more usefull if there is an args option to give event an args. For example if you are making a menu about a shop maybe and you want to only write one event then you need to send the item names to event. Or it could be an option like the qb-target. If i couldnt make you understand please look at the screenshot.
![resim_2023-07-19_022844667](https://github.com/overextended/ox_target/assets/120514341/722e4420-e82a-4b12-9b80-674219872b91)

**Comment by jag3dagster** [comment]
That's a function, not an event. And you can do that with ox_target. It's called `onSelect` like I said previously.

**Comment by LukeWasTakenn** [comment]
> Unfortunatly i cant use that function

Fortunately you can.

**Comment by thelindat** [comment]
> > That's a function, not an event. And you can do that with ox_target already, it's called `onSelect` like I said previously.
> 
> Unfortunatly i cant use that function because i need to send an argument to the event when option is clicked if i use that function than if there is multiple options player cant choose what he/she wants

Stop being obtuse. You don't need some magical "args" bullshit. What don't you understand about anything you sending being static unchanging non-arguments? What don't you understand about the message I previously sent?

> Not to mention data contains almost all the data you passed along with your option _anyway_.

We're not going to magically have a different answer for you. We are, however, going to block you from the _entire organisation_ if you continue being a nuisance.
