### ISSUE TITLE
removeGlobalPlayer

### ISSUE THREAD

**Issue by CzlowiekNinja2021** [overextended/ox_target#99]
exports.ox_target.removeGlobalPlayer("dsadsa")

api ox_target
---@param options table
function api.removeGlobalPlayer(options)
	print(json.encode(options))
    removeTarget(Players, options, GetInvokingResource())
end

option is null, removeGlobalPlayer  is not working

**Comment by thelindat** [comment]
> exports.ox_target.removeGlobalPlayer("dsadsa")
option is null, removeGlobalPlayer is not working

Because Lua uses `:` self syntax for exports.

```lua
exports.ox_target:removeGlobalPlayer("dsadsa")
```
